import os
import base64
import logging
from typing import Optional, Dict, List
from datetime import datetime
from groq import Groq
from dotenv import load_dotenv
import gradio as gr
from gtts import gTTS
from pathlib import Path
import json
import markdown

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Constants
MODEL_NAME = "meta-llama/llama-4-scout-17b-16e-instruct"
TEMP_DIR = Path("temp")
TEMP_DIR.mkdir(exist_ok=True)

# System prompts
SYSTEM_PROMPT = """You are an AI medical assistant designed to provide preliminary health information. 
When analyzing medical images or symptoms:
1. Describe what you observe in the image or from described symptoms
2. Provide possible conditions that might explain these observations
3. Suggest general self-care recommendations when appropriate
4. Always include: "I'm an AI assistant and cannot replace professional medical advice. Please consult a doctor."
5. Keep responses concise (3-4 sentences maximum)
6. Use layman's terms but maintain medical accuracy"""

CHAT_PROMPT = """You are an AI medical assistant chatting with a patient. Guidelines:
1. Be empathetic and professional
2. Ask clarifying questions if symptoms are unclear
3. Provide general health information when appropriate
4. Always remind: "Remember, I'm an AI assistant. For proper diagnosis, please consult a doctor."
5. Keep responses to 2-3 sentences maximum
6. If serious, advise immediate medical attention"""

# Initialize Groq client
try:
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
except KeyError:
    logger.error("GROQ_API_KEY not found in environment variables")
    raise
except Exception as e:
    logger.error(f"Failed to initialize Groq client: {e}")
    raise


class MedicalAssistant:
    def __init__(self):
        self.conversation_history = []
        self.current_report = {
            "patient_info": {},
            "symptoms": [],
            "images": [],
            "diagnoses": [],
            "recommendations": [],
            "timestamp": datetime.now().isoformat(),
            "disclaimer": "This report was generated by an AI assistant and is not a substitute for professional medical advice."
        }

    def add_to_history(self, role: str, content: str):
        self.conversation_history.append({"role": role, "content": content})

    def chat_response(self, user_input: str) -> str:
        """Generate text-based chat response"""
        try:
            self.add_to_history("user", user_input)
            messages = [
                {"role": "system", "content": CHAT_PROMPT},
                *self.conversation_history[-6:]
            ]

            response = client.chat.completions.create(
                messages=messages,
                model=MODEL_NAME,
                max_tokens=300,
                temperature=0.3
            )

            bot_response = response.choices[0].message.content

            if "I'm an AI assistant" not in bot_response:
                bot_response += "\n\nRemember: I'm an AI assistant and this isn't medical advice. Please consult a doctor."

            self.add_to_history("assistant", bot_response)
            self.current_report["symptoms"].append(user_input)
            self.current_report["recommendations"].append(bot_response)

            return bot_response
        except Exception as e:
            logger.error(f"Error in chat_response: {e}")
            return "Sorry, something went wrong. Please try again."

    def analyze_image(self, image_path: str, user_question: str = "") -> str:
        """Analyze medical image"""
        try:
            encoded_image = self.encode_image(image_path)
            if not encoded_image:
                return "Failed to process the image"

            self.current_report["images"].append({
                "path": image_path,
                "question": user_question
            })

            messages = [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": f"{user_question}\n\nPlease analyze this medical image."},
                        {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{encoded_image}"}}]
                }
            ]

            response = client.chat.completions.create(
                messages=messages,
                model=MODEL_NAME,
                max_tokens=512,
                temperature=0.2
            )

            bot_response = response.choices[0].message.content
            if "I'm an AI assistant" not in bot_response:
                bot_response += "\n\nImportant: I'm an AI assistant and cannot replace a doctor's evaluation."

            self.add_to_history("assistant", bot_response)
            self.current_report["diagnoses"].append(bot_response)

            return bot_response
        except Exception as e:
            logger.error(f"Error analyzing image: {e}")
            return "Image analysis failed. Please try again."

    @staticmethod
    def encode_image(image_path: str) -> Optional[str]:
        try:
            with open(image_path, "rb") as image_file:
                return base64.b64encode(image_file.read()).decode("utf-8")
        except Exception as e:
            logger.error(f"Error encoding image: {e}")
            return None

    def text_to_speech(self, text: str) -> Optional[str]:
        """Convert text to speech"""
        audio_path = TEMP_DIR / "response.mp3"
        try:
            tts = gTTS(text=text, lang='en', slow=False)
            tts.save(audio_path)
            return str(audio_path)
        except Exception as e:
            logger.error(f"TTS failed: {e}")
            return None

    def generate_report(self, format: str = "markdown") -> Dict:
        """Generate report in selected format"""
        try:
            report_data = {
                "title": "AI Medical Consultation Report",
                "date": datetime.now().strftime("%Y-%m-%d %H:%M"),
                **self.current_report
            }

            if format == "markdown":
                content = self._generate_markdown(report_data)
                return {"content": content, "file_path": None}
            elif format == "json":
                content = json.dumps(report_data, indent=2)
                return {"content": content, "file_path": None}
            else:
                raise ValueError("Unsupported format")
        except Exception as e:
            logger.error(f"Report generation failed: {e}")
            return {"content": f"Error: {e}", "file_path": None}

    def _generate_markdown(self, report_data: Dict) -> str:
        md = [
            f"# {report_data['title']}",
            f"**Date:** {report_data['date']}",""
        ]
        if report_data['symptoms']:
            md.append("## Reported Symptoms")
            md.extend(f"- {s}" for s in report_data['symptoms'])
        if report_data['diagnoses']:
            md.append("## Preliminary Assessments")
            md.extend(f"- {d}" for d in report_data['diagnoses'])
        if report_data['recommendations']:
            md.append("## Recommendations")
            md.extend(f"- {r}" for r in report_data['recommendations'])
        md.append("## Disclaimer")
        md.append(report_data["disclaimer"])
        return "\n".join(md)


def create_gradio_interface():
    assistant = MedicalAssistant()

    with gr.Blocks(title="AI Doctor", theme=gr.themes.Soft()) as app:
        gr.Markdown("# 🩺 AI Medical Assistant")
        gr.Markdown("Describe your symptoms or upload an image for preliminary assessment")

        with gr.Row():
            with gr.Column(scale=2):
                chatbot = gr.Chatbot(label="Conversation", height=400)
                msg = gr.Textbox(label="Your message", placeholder="Describe your symptoms...")
                image_input = gr.Image(type="filepath", label="Upload medical image")
                submit_btn = gr.Button("Submit", variant="primary")

            with gr.Column(scale=1):
                with gr.Tab("Report"):
                    report_format = gr.Radio(["markdown", "json"], label="Report Format", value="markdown")
                    generate_btn = gr.Button("Generate Report")
                    report_output = gr.Markdown(label="Report Preview")

                with gr.Tab("Audio Response"):
                    tts_btn = gr.Button("🔊 Generate Voice Response")
                    tts_output = gr.Audio(label="Doctor's Response", interactive=False)

        def respond(message: str, image: Optional[str], history: List):
            if not message and not image:
                return history, "Please provide symptoms or an image"
            response = assistant.analyze_image(image, message) if image else assistant.chat_response(message)
            history.append((message, response))
            return history, ""

        def generate_report(format: str):
            report = assistant.generate_report(format)
            return report["content"]

        def generate_tts_response(history: List):
            if not history:
                return None
            last_response = history[-1][1]
            return assistant.text_to_speech(last_response)

        msg.submit(respond, [msg, image_input, chatbot], [chatbot, msg])
        submit_btn.click(respond, [msg, image_input, chatbot], [chatbot, msg])
        generate_btn.click(generate_report, inputs=report_format, outputs=report_output)
        tts_btn.click(generate_tts_response, inputs=chatbot, outputs=tts_output)

    return app


if __name__ == "__main__":
    if "GROQ_API_KEY" not in os.environ:
        raise ValueError("Please set GROQ_API_KEY in your .env file")

    interface = create_gradio_interface()
    print("\nApp running at: http://127.0.0.1:7860")
    interface.launch(server_name="0.0.0.0", server_port=7860, share=False, show_error=True)